Change createAndAttch from arror function
Due to error on build:

ERROR in ./src/utils.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\Greg\Desktop\Code\JSFUN_final_projects\Final_Project_ACC\src\utils.js: Support for the experimental syntax 'classProperties' isn't currently enabled (49:20):

MovieContainer method createAndAttch causes an error at build time as an arrow function. Changing to standard function declaration resolves this.